In [72]:
import re 
import string 
import mlflow 
import nltk
import numpy as np 
import pandas as pd 
import mlflow.sklearn 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer

In [73]:
df =pd.read_csv('IMDB.csv')

In [74]:
df = df.sample(500)
df.to_csv('data.csv',index=False)

In [75]:
df.head()

                                                review sentiment
465  This BBC series is excellent. I am no Paleonto...  positive
32   this became a cult movie in chinese college st...  negative
889  "Journey of Hope" tells of a poor Turkish fami...  positive
202  Beware My Lovely originated from a play writte...  positive
945  A Disney movie that dares to do something diff...  positive

In [76]:
english_stopwords = set(stopwords.words('english'))
print(english_stopwords)

{'when', "that'll", 'his', "aren't", 'shouldn', 'between', "they'd", 'is', 'than', 'he', 'weren', 'had', 'off', "it'd", 'shan', "isn't", 'only', 'below', 've', 'am', "you've", 'while', 'from', 'until', 'where', 'can', "they're", 'herself', 'mustn', 'during', 'ours', 'through', "we've", 'be', 'd', 'at', 'yours', "he's", "i'd", 'then', 'what', 'she', 'have', 'against', "he'd", 'hers', 'me', 'the', 'why', 'wasn', 'to', 'before', 'that', 'into', "needn't", 'does', 'down', "shan't", 'or', 'which', 'up', 'who', 'ain', 'didn', 'just', 'there', "i'll", 'wouldn', 'because', "you'd", "hasn't", 'for', 'doing', 'itself', 'its', 'how', 'an', 'll', "i'm", 'with', "shouldn't", 'been', 'will', 'whom', 'further', "couldn't", 'their', 'nor', "she'd", 'don', 'by', "mightn't", 'isn', 'other', "she's", "haven't", 'too', 'same', 'once', 'needn', 'ourselves', 'your', "hadn't", 'you', 'himself', 'this', 'above', 'these', "you're", "it's", 't', 'are', 'more', 'over', 'it', 'y', 'yourselves', "mustn't", "wouldn't", 'those', 'such', 'having', 'most', 'being', 'about', 'no', 'our', 'mightn', 'm', "didn't", 'in', 'out', "she'll", 'aren', 'my', 'hasn', 'a', "we'd", "we'll", 'won', 'theirs', "don't", 'both', 're', 'now', 'couldn', "i've", 'were', "weren't", 'again', 'all', 'themselves', 'o', 'here', 'some', "won't", "they've", 'myself', "doesn't", 'has', 'haven', 'each', 'very', 'did', 'and', "it'll", 'was', "you'll", 'him', 'them', 'if', 'her', 'few', 'should', 'we', 'under', 'yourself', 'not', "they'll", 'as', 's', 'of', 'do', "wasn't", 'ma', "he'll", 'any', "should've", 'after', 'so', "we're", 'they', 'i', 'but', 'hadn', 'own', 'doesn', 'on'}

In [79]:
import nltk
  >>> nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...

True

In [80]:
# data preprocessing

# Define text preprocessing functions
def lemmatization(text):
    """Lemmatize the text."""
    lemmatizer = WordNetLemmatizer()
    text = text.split()
    text = [lemmatizer.lemmatize(word) for word in text]
    return " ".join(text)

def remove_stop_words(text):
    """Remove stop words from the text."""
    stop_words = set(stopwords.words("english"))
    text = [word for word in str(text).split() if word not in stop_words]
    return " ".join(text)

def removing_numbers(text):
    """Remove numbers from the text."""
    text = ''.join([char for char in text if not char.isdigit()])
    return text

def lower_case(text):
    """Convert text to lower case."""
    text = text.split()
    text = [word.lower() for word in text]
    return " ".join(text)

def removing_punctuations(text):
    """Remove punctuations from the text."""
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
    text = text.replace('؛', "")
    text = re.sub('\s+', ' ', text).strip()
    return text

def removing_urls(text):
    """Remove URLs from the text."""
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

def normalize_text(df):
    """Normalize the text data."""
    try:
        df['review'] = df['review'].apply(lower_case)
        df['review'] = df['review'].apply(remove_stop_words)
        df['review'] = df['review'].apply(removing_numbers)
        df['review'] = df['review'].apply(removing_punctuations)
        df['review'] = df['review'].apply(removing_urls)
        df['review'] = df['review'].apply(lemmatization)
        return df
    except Exception as e:
        print(f'Error during text normalization: {e}')
        raise

<>:32: SyntaxWarning: invalid escape sequence '\s'
<>:32: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21980\3798096103.py:32: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub('\s+', ' ', text).strip()

In [81]:
df = normalize_text(df)
df.head()

                                                review sentiment
465  bbc series excellent paleontologist series giv...  positive
32   became cult movie chinese college student thou...  negative
889  journey hope tell poor turkish family odyssey ...  positive
202  beware lovely originated play written mel dine...  positive
945  disney movie dare something different least aw...  positive

In [82]:
df['sentiment'].value_counts()

sentiment
positive    250
negative    250
Name: count, dtype: int64

In [83]:
x = df['sentiment'].isin(['positive','negative'])
df = df[x]

In [84]:
df['sentiment'] = df['sentiment'].map({'positive':1,'negative':0})
df.head()

                                                review  sentiment
465  bbc series excellent paleontologist series giv...          1
32   became cult movie chinese college student thou...          0
889  journey hope tell poor turkish family odyssey ...          1
202  beware lovely originated play written mel dine...          1
945  disney movie dare something different least aw...          1

In [85]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [86]:
vectorizer=CountVectorizer(max_features=100)
x = vectorizer.fit_transform(df['review'])
y = df['sentiment']

In [87]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
import dagshub

mlflow.set_tracking_uri('keep_your_uri_here')
dagshub.init(repo_owner='your_username', repo_name='MLOps-Capstone-Project', mlflow=True)


# mlflow.set_experiment("Logistic Regression Baseline")
mlflow.set_experiment("Logistic Regression Baseline")

Accessing as nishchalacharya

Initialized MLflow to track repo "nishchalacharya/MLOps-Capstone-Project"

Repository nishchalacharya/MLOps-Capstone-Project initialized!

2026/04/02 14:53:50 INFO mlflow.tracking.fluent: Experiment with name 'Logistic Regression Baseline' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/489462bddd6147f195806f27e547a08a', creation_time=1775120929898, experiment_id='0', last_update_time=1775120929898, lifecycle_stage='active', name='Logistic Regression Baseline', tags={}, workspace='default'>

In [89]:
import mlflow
import logging
import os
import time
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

logging.info("Starting MLflow run...")


with mlflow.start_run():
    start_time = time.time()
    try:
        logging.info("Logging preprocessing parameters...")
        mlflow.log_param("vectorizer", "Bag of Words")
        mlflow.log_param("num_features", 100)
        mlflow.log_param("test_size", 0.25)

        logging.info("Initializing Logistic Regression model...")
        model = LogisticRegression(max_iter=1000)  # Increase max_iter to prevent non-convergence issues

        logging.info("Fitting the model...")
        model.fit(X_train, y_train)
        logging.info("Model training complete.")

        logging.info("Logging model parameters...")
        mlflow.log_param("model", "Logistic Regression")

        logging.info("Making predictions...")
        y_pred = model.predict(X_test)


        logging.info("Calculating evaluation metrics...")
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        logging.info("Logging evaluation metrics...")
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)


        logging.info("Saving and logging the model...")
        mlflow.sklearn.log_model(model, "model")

        # Log execution time
        end_time = time.time()
        logging.info(f"Model training and logging completed in {end_time - start_time:.2f} seconds.")

        # Save and log the notebook
        # notebook_path = "exp1_baseline_model.ipynb"
        # logging.info("Executing Jupyter Notebook. This may take a while...")
        # os.system(f"jupyter nbconvert --to notebook --execute --inplace {notebook_path}")
        # mlflow.log_artifact(notebook_path)

        # logging.info("Notebook execution and logging complete.")

        # Print the results for verification
        logging.info(f"Accuracy: {accuracy}")
        logging.info(f"Precision: {precision}")
        logging.info(f"Recall: {recall}")
        logging.info(f"F1 Score: {f1}")

    except Exception as e:
        logging.error(f"An error occurred: {e}", exc_info=True)

2026-04-02 15:01:28,415 - INFO - Starting MLflow run...
2026-04-02 15:01:30,256 - INFO - Logging preprocessing parameters...
2026-04-02 15:01:31,539 - INFO - Initializing Logistic Regression model...
2026-04-02 15:01:31,540 - INFO - Fitting the model...
2026-04-02 15:01:31,565 - INFO - Model training complete.
2026-04-02 15:01:31,566 - INFO - Logging model parameters...
2026-04-02 15:01:31,965 - INFO - Making predictions...
2026-04-02 15:01:31,967 - INFO - Calculating evaluation metrics...
2026-04-02 15:01:31,973 - INFO - Logging evaluation metrics...
2026-04-02 15:01:33,631 - INFO - Saving and logging the model...
2026/04/02 15:01:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/02 15:01:37 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026-04-02 15:01:43,970 - INFO - Model training and logging completed in 13.71 seconds.
2026-04-02 15:01:43,970 - INFO - Accuracy: 0.59
2026-04-02 15:01:43,971 - INFO - Precision: 0.5689655172413793
2026-04-02 15:01:43,972 - INFO - Recall: 0.673469387755102
2026-04-02 15:01:43,972 - INFO - F1 Score: 0.616822429906542

🏃 View run traveling-roo-156 at: https://dagshub.com/nishchalacharya/MLOps-Capstone-Project.mlflow/#/experiments/0/runs/daca0f6fce124785921189e8b05c7d5e
🧪 View experiment at: https://dagshub.com/nishchalacharya/MLOps-Capstone-Project.mlflow/#/experiments/0